import random

# SETTING LISTS
more_than_one = {
    "some", "a few", "a couple of", "a pair of", "a trio of", "a group of", "a bunch of",
    "a cluster of", "a collection of", "a set of", "a series of", "a sequence of",
    "a string of", "a line of", "a row of", "a chain of", "a circle of", "many", "several",
    "a lot of", "lots of", "plenty of", "a ton of", "too many", "not enough",
    "a handful of", "a heap of", "a stack of", "100", "200", "300", "500", "1000", "a stupid amount of",
    "a ridiculous amount of", "a massive amount of", "a huge amount of", "a large amount of",
    "a small amount of", "a tiny amount of", "a minuscule amount of", "a microscopic amount of",
    "a negligible amount of", "a significant amount of", "an insignificant amount of",
    "an army of", "a parade of", "a swarm of", "a fleet of", "a horde of", "a mob of", "a multitude of",
    "a plethora of", "an abundance of", "a scattering of", "a smattering of", "a sprinkle of", "a dash of",
    "a flood of", "a wave of", "a sea of", "a forest of", "a galaxy of", "a constellation of", "a barrage of",
    "a deluge of", "a glut of", "a surplus of", "a deficit of", "a shortage of", "a trickle of", "a handful and a half of",
    "a baker’s dozen of", "a double helping of", "a triple serving of", "a mountain of", "a pile of", "a pyramid of",
    "a cornucopia of", "a zoo of", "a circus of", "a festival of", "a medley of", "a mishmash of", "a jumble of",
    "a patchwork of", "a kaleidoscope of", "a spectrum of", "a rainbow of", "a cacophony of", "a symphony of",
    "a collection and a half of", "a double stack of", "a gross of", "a metric ton of", "a truckload of", "a boatload of",
    "a bucket of", "a crate of", "a barrel of", "a vat of", "a crate and a half of", "a bushel of", "a peck of",
    "a cluster and a half of", "a couple dozen", "a few dozen", "a hundred or so", "a million", "infinite", "countless",
    "uncountable", "innumerable", "endless", "limitless", "myriad", "oodles of", "gobs of", "scads of", "loads of",
    "tons of", "heaps of", "stacks of", "mountains of", "oceans of", "galaxies of"
    #not more than one, but where an 's' is added to the end of the object
    "a fusion of",  "a mixture of", "a combination of", "a blend of", "a hybrid of", "a twist on", "a riff on",
    "a take on", "a reinterpretation of", "a branch of", "a lineage of", "a descendant of", "a predecessor of",
    "a successor to", "a remnant of", "a relic of", "a leftover of","the story that never was about",
    "the myth that never faded about", "the tale that never ended involving", "the myth that became real about",
    "the tale that told itself involving"
}

obscure_setting = {
    "some kind of", "a type of", "a sort of", "a form of", "a variety of", "a breed of",
    "a style of", "a kind of", "a class of", "a category of", "a genre of", "a species of",
    "the attack of the", "the discovery of the", "the adventure of the", "the journey of the", "the quest for the",
    "the search for the", "the exploration of the", "the legend of the", "the myth of the", "the tale of the",
    "this: once upon a time, there was a", "the rise of the", "the fall of the", "the return of the",
    "the revenge of the", "the prophecy of the", "the curse of the", "the blessing of the", "the awakening of the",
    "the secret of the", "the mystery of the", "the invention of the", "the escape from the", "the invasion of the",
    "the defense of the", "the last stand of the", "the first meeting of the", "the reunion of the", "the betrayal of the",
    "the alliance of the", "the formation of the", "the dissolution of the", "the transformation of the",
    "the metamorphosis of the", "the evolution of the", "the extinction of the", "the rebirth of the",
    "the day the world ended", "the day the world began", "the time before time", "the age of the", "the era of the",
    "the dawn of the", "the dusk of the", "the twilight of the", "the golden age of the", "the dark age of the",
    "the silver age of the", "the iron age of the", "the stone age of the", "the digital age of the",
    "the space age of the", "the forgotten age of the", "the lost age of the", "the forbidden age of the",
    "the hidden age of the", "the secret age of the", "the legendary age of the", "the mythical age of the",
    "the ancient age of the", "the future age of the", "the parallel world of the", "the alternate reality of the",
    "the simulation of the", "the dream of the", "the nightmare of the", "the hallucination of the", "the illusion of the",
    "the paradox of the", "the impossible story of the", "the untold story of the", "the unwritten story of the",
    "the unfinished story of the", "the endless story of the", "the infinite story of the", "the neverending story of the",
    "the legend that never died, the hero wielded a", "a kung fu fight where, as a weapon, you're using a",
    "a cowboy who's weapon of choice is a", "a pirate who sails the seas with a", "a ninja who uses a",
    "an example of", "a specimen of", "a manifestation of", "an instance of", "a demonstration of", "an embodiment of",
    "a representation of", "an incarnation of", "a version of", "a flavor of", "a model of", "a prototype of",
    "a sample of", "a case of", "a case study of", "a depiction of", "a portrait of", "a rendering of", "a vision of",
    "a glimpse of", "a shadow of", "a reflection of", "a memory of", "a rumor of", "a whisper of", "a legend of",
    "a myth of", "a tale of", "a rumor about", "a story about", "a report of", "a rumor regarding", "a fable of",
    "a saga of", "a chronicle of", "a narrative of", "a rumor surrounding", "a story involving", "a rumor concerning",
    "a rumor featuring a", "a variant of", "a mutation of", "a deviation from a usual", "a reimagining of the",
    "a version of",  "a remixed form of", "a shadowy form of", "a rumored form of", "a supposed form of",
    "a possible form of", "a theoretical form of", "a hypothetical form of", "a legendary form of",
    "a forgotten form of", "a rediscovered form of", "a rumored type of", "a mysterious type of", "an unknown type of",
    "an unclassified type of", "an unidentifiable type of", "an unnamable type of"
}


# DESCRIPTOR LISTS
descriptors = {
    "aquatic", "terrestrial", "flying", "burrowing", "swimming", "climbing", "running", "jumping",
    "crawling", "slithering", "walking", "creeping", "scurrying", "sneaking", "hopping", "amphibious",
    "insectoid", "reptilian", "avian", "mammalian", "small", "tiny", "miniature", "little", "petite",
    "diminutive", "compact", "slight", "narrow", "thin", "skinny", "lean", "slender", "graceful",
    "agile", "quick", "elegant", "delicate", "fragile", "brittle", "sturdy", "robust", "durable",
    "strong", "powerful", "mighty", "formidable", "intimidating", "fearsome", "terrifying",
    "horrifying", "scary", "creepy", "spooky", "eerie", "ghostly", "phantasmal", "spectral",
    "wraithlike", "ethereal", "aerial", "airy", "light", "heavy", "dense", "solid", "liquid",
    "gaseous", "plasma", "crystalline", "amorphous", "granular", "powdery", "sandy", "rocky",
    "superfluous", "muddy", "giant", "huge", "enormous", "massive", "colossal", "titanic", "monstrous",
    "behemoth", "leviathan", "gargantuan", "monolithic", "towering", "lofty", "high", "elevated",
    "raised", "uplifted", "soaring", "sky-high", "floating", "sunken", "submerged", "underwater",
    "mountainous", "volcanic", "icy", "mystical", "ancient", "forgotten", "hidden", "enchanted",
    "cursed", "abandoned", "mysterious", "legendary", "mythical", "haunted", "magical", "pristine",
    "untouched", "lush", "barren", "desolate", "verdant", "oceanic", "forest", "desert", "tropical",
    "polar", "urban", "rural", "industrial", "futuristic", "steampunk", "cyberpunk",  "gigantic",
    "post-apocalyptic", "medieval", "renaissance", "baroque", "gothic", "art deco", "art nouveau",
    "modern", "contemporary", "vintage", "retro", "classic", "antique", "primal", "elemental",
    "cosmic", "celestial", "stellar", "galactic", "cosmological", "intergalactic", "interstellar",
    "extraterrestrial", "alien", "otherworldly", "supernatural", "paranormal", "occult", "esoteric",
    "arcane", "mystic", "spiritual", "divine", "holy", "sacred", "profane", "blessed", "cursed",
    "enchanted", "bewitched", "charmed", "hexed", "spellbound", "transformed", "metamorphosed",
    "shapeshifted", "illusionary", "phantasmal", "spectral", "ghostly", "wraithlike", "ethereal",
    "slippery", "icy", "snowy", "rainy", "stormy", "windy", "foggy", "cloudy", "sunny", "clear",
    "bright", "dark", "dim", "shadowy", "gloomy", "twilight", "dawn", "dusk", "noon", "midnight",
    "sunrise", "sunset", "daytime", "nighttime", "morning", "afternoon", "evening", "late", "early",
    "recent", "ancient", "old", "new", "fresh", "stale", "rotten", "decayed", "rusty", "corroded",
    "weathered", "worn", "aged", "pickle-ridden", "wonky", "quirky", "odd", "strange", "weird",
    "bizarre", "peculiar", "unusual", "abnormal", "anomalous", "irregular", "unexpected",
    "surprising", "astonishing", "amazing", "incredible", "unbelievable", "extraordinary",
    "remarkable", "noteworthy", "significant", "important", "valuable", "precious", "treasured",
    "cherished", "beloved", "adored", "revered", "respected", "anime", "upside-down", "inside-out",
    "backwards", "sideways", "twisted", "contorted", "deformed", "grotesque", "monstrous",
    "hideous", "ugly", "beautiful", "handsome", "pretty", "gorgeous", "stunning", "attractive",
    "charming", "alluring", "captivating", "enchanting", "bewitching", "spellbinding", "mesmerizing",
    "hypnotic", "transfixing", "fascinating", "interesting", "intriguing", "engaging", "absorbing",
    "gripping", "hurt", "injured", "wounded", "damaged", "broken", "shattered", "cracked",
    "splintered", "fractured", "mangled", "disfigured", "maimed", "gold-plated", "diamond-encrusted",
    "ruby-studded", "sapphire-embedded", "emerald-adorned", "pearl-inlaid", "platinum-coated",
    "bronze-cast", "iron-forged", "steel-reinforced", "copper-wired", "brass-trimmed", "silver-lined",
    "gold-leafed", "obsidian-bladed", "crystal-tipped", "jade-etched", "ivory-carved", "bone-handled",
    "wooden", "leather-bound", "fabric-covered", "metallic", "plastic", "glass", "ceramic",
    "porcelain", "stone", "marble", "granite", "limestone", "sandstone", "slate", "chalk", "clay",
    "mud", "dirt", "soil", "ash", "charcoal", "coal", "iron", "steel", "aluminum", "copper", "bronze",
    "brass", "silver", "gold", "platinum", "diamond", "ruby", "sapphire", "emerald", "pearl", "topaz",
    "evil", "wicked", "malicious", "sinister", "nefarious", "villainous", "diabolical", "malevolent",
    "ineffective", "inefficient", "unproductive", "counterproductive", "harmful", "dangerous", "dumb",
    "stupid", "foolish", "ignorant", "naive", "gullible", "felonius", "criminal", "devious", "sneaky",
    "sly", "cunning", "crafty", "wily", "shrewd", "clever", "intelligent", "smart", "brilliant",
    "genius", "wise", "knowledgeable", "learned", "erudite", "sophisticated", "cultured", "refined",
    "polished", "elegant", "graceful", "stylish", "fashionable", "chic", "trendy", "hip", "cool",
    "pirate", "ninja", "samurai", "cowboy", "viking", "knight", "warrior", "gladiator", "spartan",
    "mercenary", "assassin", "rogue", "thief", "bandit", "outlaw", "rebel", "revolutionary",
    "gold-adorned", "silver-embellished", "bronze-etched", "platinum-engraved", "diamond-studded",
    "ruby-encrusted", "sapphire-embedded", "emerald-inlaid", "pearl-trimmed", "topaz-set",
    "amethyst-ornamented", "opal-decorated", "garnet-accoutered", "peridot-embellished",
    "chiaroscuro", "neon-lit", "cybernetic", "biomechanical", "steampunk-inspired",
    "retro-futuristic", "sci-fi", "fantasy", "horror", "post-apocalyptic", "dystopian",
    "utopian", "surrealist", "absurdist", "existential", "philosophical", "satirical",
    "parodic", "ironic", "self-aware", "meta", "fourth-wall-breaking", "slapstick", "dark comedy",
    "romantic comedy", "action-packed", "adventure-filled", "mystery-solving", "detective noir",
    "psychological thriller", "supernatural horror", "gothic horror", "body horror", "slasher",
    "found footage", "mockumentary", "animated", "live-action", "stop-motion", "claymation",
    "hand-drawn", "pixel art", "3D animated", "CGI", "motion capture", "rotoscoped", "silhouette",
    "shadow puppetry", "cutout animation", "paper craft", "origami", "collage", "mixed media",
    "photographic", "digital", "traditional", "impressionistic", "expressionistic", "abstract",
    "surreal", "cubist", "futurist", "dadaist", "pop art", "street art", "graffiti", "mural",
    "installation art", "performance art", "conceptual art", "minimalist", "maximalist",
    "baroque", "rococo", "neoclassical", "romantic", "realist", "impressionist", "post-impressionist",
    "modernist", "postmodernist", "contemporary", "avant-garde", "art deco", "art nouveau",
    "brutalist", "deconstructivist", "futuristic", "cyberpunk", "steampunk", "dieselpunk",
    "clockpunk", "biopunk", "solarpunk", "darksynth", "retrowave", "synthwave", "vaporwave",
    "lo-fi", "chiptune", "8-bit", "pixelated", "glitch art", "datamoshing", "analog", "digital",
    "handmade", "craft", "folk", "naive", "outsider", "visionary", "psychedelic", "kitsch",
    "gothic", "renaissance", "medieval", "ancient", "tribal", "indigenous", "folk art", "naive art",
    "outsider art", "visionary art", "psychedelic", "kitsch", "camp", "lowbrow", "highbrow",
    "campy", "quirky", "whimsical", "playful", "childlike", "naive", "innocent", "sophisticated",
    "elegant", "refined", "polished", "graceful", "stylish", "chic", "trendy", "hip", "cool",
    "retro", "vintage", "nostalgic", "timeless", "classic", "futuristic", "space-age", "cyberpunk",
    "steampunk", "dieselpunk", "clockpunk", "biopunk", "solarpunk", "darksynth", "retrowave",
    "aquamarine-ornamented", "tourmaline-etched", "zircon-studded", "tanzanite-embedded",
    "moonstone-inlaid", "sunstone-trimmed", "lapis lazuli-ornamented", "malachite-etched",
    "turquoise-studded", "onyx-embedded", "jasper-inlaid", "agate-trimmed", "carnelian-ornamented",
    "bloodstone-etched", "chrysoprase-studded", "chalcedony-embedded", "calcite-inlaid",
    "fluorite-trimmed", "hematite-ornamented", "obsidian-etched", "pyrite-studded", "quartz-embedded",
    "smoky quartz-inlaid", "rose quartz-trimmed", "clear quartz-ornamented", "ametrine-etched",
    "smoky", "rose", "clear", "jumbled", "confused", "disordered", "chaotic", "mixed-up", "disorganized",
    "haphazard", "random", "scattered", "dispersed", "spread out", "disheveled", "messy", "untidy",
    "sloppy", "careless", "negligent", "slovenly", "unruly", "unmanageable", "uncontrollable",
    "glowing", "bioluminescent", "radioactive", "shimmering", "sparkling", "glittering", "luminescent",
    "iridescent", "prismatic", "chromatic", "color-shifting", "holographic", "pixelated", "glitched",
    "fractured", "fragmented", "patchwork", "stitched", "quilted", "patched", "tattered", "frayed",
    "weather-beaten", "sun-bleached", "frostbitten", "overgrown", "mossy", "lichen-covered", "crumbling",
    "ruined", "dilapidated", "ramshackle", "makeshift", "jury-rigged", "improvised", "cobbled-together",
    "clockwork", "mechanical", "steam-powered", "gear-driven", "spring-loaded", "magnetized", "levitating",
    "hovering", "floating", "suspended", "anchored", "rooted", "buried", "entombed", "enshrouded", "veiled",
    "masked", "disguised", "camouflaged", "invisible", "transparent", "translucent", "opaque", "mirrored",
    "reflective", "shadow-cast", "backlit", "spotlit", "flickering", "strobing", "pulsing", "glowing",
    "vibrating", "resonant", "echoing", "dissonant", "harmonious", "melodic", "cacophonous", "discordant",
    "noisy", "silent", "mute", "wordless", "voiceless", "screaming", "howling", "whispering", "murmuring",
    "babbling", "gurgling", "bubbling", "frothing", "foaming", "effervescent", "fizzy", "carbonated", "syrupy",
    "sticky", "gooey", "slimy", "viscous", "gelatinous", "oozing", "dripping", "melting", "smoldering", "smoky",
    "sooty", "charred", "burnt", "scorched", "blistered", "crackling", "popping", "sizzling", "steaming", "boiling",
    "frozen", "frosty", "icy-hot", "aromatic", "fragrant", "pungent", "acrid", "musty", "moldy", "earthy", "woody",
    "spicy", "peppery", "herbal", "floral", "citrusy", "zesty", "tangy", "savory", "umami", "sweet", "sour", "bitter",
    "salty", "metallic-tasting", "chalky", "gritty", "sandy-textured", "velvety", "silky", "satiny", "slick", "greasy",
    "oily", "waxy", "polished", "lacquered", "varnished", "enameled", "gilded", "silvered", "bronzed", "coppery", "rusted",
    "patinaed", "verdigris", "corroded", "pitted", "scarred", "engraved", "embossed", "etched", "carved", "inscribed",
    "runed", "sigiled", "glyph-marked", "tattooed", "branded", "stamped", "sealed", "locked", "unlocked", "open", "ajar",
    "closed", "sealed shut", "barred", "guarded", "watched", "unwatched", "abandoned", "forgotten", "remembered",
    "celebrated", "feared", "worshipped", "taboo", "forbidden", "sacrosanct", "profane", "cursed", "blessed", "enchanted",
    "bewitched", "haunted", "possessed", "infested", "infected", "plagued", "contaminated", "purified", "cleansed",
    "sanctified", "desecrated", "polluted", "toxic", "radioactive", "mutated", "evolved", "ancient-future", "timeless",
    "eternal", "ephemeral", "fleeting", "momentary", "perpetual", "infinite", "endless", "cyclical", "spiraling",
    "labyrinthine", "maze-like", "tangled", "knotted", "braided", "woven", "interlaced", "entwined", "coiled", "spiraled",
    "twisted", "contorted", "warped", "distorted", "bent", "crooked", "askew", "lopsided", "off-kilter", "topsy-turvy",
    "topsy-turvied", "inside-outed", "upside-downed", "mirror-imaged", "palindromic", "reversed", "inverted", "negative",
    "opposite", "contradictory", "paradoxical", "impossible", "unreal", "dreamlike", "nightmarish", "hallucinatory", "surreal",
    "absurd", "nonsensical", "whimsical", "fantastical", "mythic", "legendary", "fabled", "storybook", "fairy-tale", "epic",
    "heroic", "tragic", "comic", "satirical", "parodic", "ironic", "sarcastic", "deadpan", "tongue-in-cheek", "self-aware",
    "meta", "fourth-wall-breaking", "sloppy", "careless", "negligent", "slovenly", "unruly", "unmanageable", "uncontrollable"
}

pop_culture_list = {
    "Star Wars", "Lord of the Rings", "Game of Thrones", "Elden Ring", "Marvel Comics", "DC Comics",
    "Pirates of the Caribbean", "Indiana Jones", "Minecraft", "Dark Souls", "Bloodborne", "Sekiro",
    "Cyberpunk", "Star Trek", "Doctor Who", "The Witcher", "Binding of Isaac", "Deep Rock Galactic",
    "The Legend of Zelda", "Super Mario", "Pokémon", "Final Fantasy", "Kingdom Hearts",
    "Assassin's Creed", "Halo", "Overwatch", "World of Warcraft", "Diablo", "Street Fighter",
    "Mortal Kombat", "Tekken", "Gears of War", "Mass Effect", "Bioshock", "Fallout",
    "The Elder Scrolls", "Dungeons & Dragons", "Magic: The Gathering",
    "Warhammer 40,000", "The Matrix", "Blade Runner", "Ghost in the Shell", "Akira", "Naruto",
    "One Piece", "Dragon Ball Z", "Attack on Titan", "Evil Dead", "The Walking Dead",
    "Stranger Things", "Breaking Bad", "Adventure Time", "Rick and Morty", "Gravity Falls", "Terminator",
    "Jurassic Park", "Transformers", "Fast and Furious", "Shakespeare", "Dune", "The Hitchhiker's Guide to the Galaxy",
    "The Simpsons", "SpongeBob SquarePants", "Over the Garden Wall", "Samurai Jack", "Teenage Mutant Ninja Turtles",
    "Power Rangers", "Sailor Moon", "Dragon Ball", "One Piece", "Naruto", "My Neighbor Totoro", "Spirited Away", "Princess Mononoke",
    "Cowboy Bebop", "Samurai Champloo", "Wallace and Gromit", "Coraline", "The Nightmare Before Christmas", "LEGO", "The Incredibles",
    "Toy Story", "Monsters, Inc.", "Finding Nemo", "Shrek", "Kung Fu Panda", "The Iron Giant", "Tron", "The Goonies", "Labyrinth",
    "The Dark Crystal", "Fantastic Mr. Fox", "Spider-Man: Spider-Verse series", "Batman: The Animated Series", "X-Men", "Gargoyles",
    "DuckTales", "Mega Man", "Castlevania", "Metroid", "Jet Set Radio", "Okami", "Katamari Damacy", "Parappa the Rapper",
    "Viewtiful Joe", "Cuphead", "Hollow Knight", "Undertale", "Journey", "Limbo", "Psychonauts", "Rayman", "Banjo-Kazooie",
    "Crash Bandicoot", "Spyro the Dragon", "Ratchet & Clank", "EarthBound", "Animal Crossing", "Stardew Valley", "Harvest Moon",
    "The Sims", "Portal", "Half-Life", "Team Fortress 2", "BioShock Infinite", "Mirror's Edge", "No More Heroes", "Devil May Cry",
    "Monster Hunter", "Phoenix Wright: Ace Attorney", "Professor Layton", "Tetris", "Pac-Man", "Space Invaders", "Galaga", "Asteroids",
    "Frogger", "Q*bert", "Donkey Kong Country", "The Legend of Zelda",
    #other stylistic choices
    "surreal", "absurdist", "existential", "philosophical", "satirical", "parodic",
    "ironic", "self-aware", "meta", "fourth-wall-breaking", "slapstick", "dark comedy",
    "romantic comedy", "action-packed", "adventure-filled", "mystery-solving", "detective noir",
    "psychological thriller", "supernatural horror", "gothic horror", "body horror", "slasher",
    "found footage", "mockumentary", "animated", "live-action", "stop-motion", "claymation",
    "hand-drawn", "pixel art", "3D animated", "CGI", "motion capture", "rotoscoped", "silhouette",
    "shadow puppetry", "cutout animation", "paper craft",
    "origami", "collage", "mixed media", "photographic", "digital", "traditional", "impressionistic",
    "expressionistic", "abstract", "surreal", "cubist", "futurist", "dadaist", "pop art",
    "street art", "graffiti", "mural", "installation art", "performance art", "conceptual art",
    "minimalist", "maximalist", "baroque", "rococo", "neoclassical", "romantic", "realist",
    "impressionist", "post-impressionist", "modernist", "postmodernist", "contemporary", "avant-garde",
    "art deco", "art nouveau", "gothic", "renaissance", "medieval", "ancient", "tribal",
    "indigenous", "folk art", "naive art", "outsider art", "craftsmanship",
    "handmade", "artisan", "homemade", "vintage", "retro", "antique", "rustic", "shabby chic",
    "bohemian", "eclectic", "kitsch", "camp", "quirky", "whimsical", "playful", "childlike",
    "nostalgic", "sentimental", "romantic", "melancholic", "bittersweet", "poignant", "heartwarming",
    "uplifting", "inspirational", "motivational", "empowering", "transformative", "life-changing",
    "mind-expanding", "eye-opening", "thought-provoking", "philosophical", "intellectual",
    "cerebral", "esoteric", "arcane", "mystical", "spiritual", "metaphysical", "transcendent",
    "enlightening", "illuminating", "revelatory", "epiphanic", "cathartic", "therapeutic", "healing",
    "redemptive", "purifying", "cleansing", "catholic", "universal", "timeless", "eternal", "infinite",
    "boundless", "limitless", "unfathomable", "cosmic", "celestial", "stellar", "galactic", "universal",
    "multiversal", "omnipresent"
}


# OBJECT LISTS
items = {
    "just a lil guy", "friend", "companion", "sidekick", "ally", "partner", "buddy", "mountain",
    "creature", "wizard", "sorcerer", "warrior", "knight", "rogue", "assassin", "mage", "priest",
    "healer", "tank", "dps", "support", "adventurer", "explorer", "scout", "ranger", "hunter",
    "forager", "gatherer", "miner", "blacksmith", "carpenter", "builder", "engineer", "inventor",
    "alchemist", "enchanter", "artificer", "tinkerer", "mechanic", "technician", "pilot", "captain",
    "commander", "general", "leader", "chief", "boss", "king", "queen", "prince", "princess",
    "goblin", "orc", "troll", "ogre", "golem", "elemental", "sprite", "fairy", "nymph", "dryad",
    "pixie", "imp", "demon", "angel", "devil", "djinn", "genie", "vampire", "werewolf", "zombie",
    "sylph", "undine", "phoenix", "dragon", "wyvern", "griffin", "chimera", "manticore", "minotaur",
    "centaur", "satyr", "faun", "mermaid", "siren", "kraken", "leviathan", "behemoth", "potion",
    "elixir", "ice sculpture", "firework", "magic scroll", "ancient artifact", "mysterious relic",
    "enchanted weapon", "cursed item", "legendary treasure", "mythical beast", "magical creature",
    "supernatural entity", "paranormal phenomenon", "occult symbol", "esoteric knowledge",
    "arcane ritual", "mystic artifact", "spiritual totem", "divine relic", "holy symbol",
    "sacred text", "profane object", "blessed charm", "cursed talisman", "enchanted amulet",
    "bewitched ring", "Hercules", "Thor", "Zeus", "Poseidon", "Hades", "Athena", "Apollo",
    "Artemis", "Ares", "Demeter", "Dionysus", "Hermes", "Hephaestus", "Hera", "Loki", "Odin",
    "Freya", "ninja", "samurai", "ronin", "shogun", "geisha", "yokai", "kami", "shinto priest",
    "bushi", "kunoichi", "shinobi", "swordsman", "swordfighter", "swordmaster", "swordsmith",
    "stage show", "magic trick", "illusion", "card game", "board game", "video game",
    "role-playing game", "tabletop game", "strategy game", "puzzle game", "adventure game",
    "puzzle", "quest", "mission", "weapon", "armor", "shield", "helmet", "boots", "gloves", "cloak",
    "robe", "hat", "mask", "amulet", "mirror", "ring", "necklace", "bracelet", "earrings", "brooch",
    "pendant", "charm", "trinket", "talisman", "totem", "idol", "figurine", "statue", "sculpture",
    "painting", "drawing", "sketch", "illustration", "mural", "graffiti", "carving", "engraving",
    "etching", "print", "poster", "banner", "flag", "tapestry", "rug", "carpet", "cloth",
    "fabric", "textile", "leather", "fur", "feather", "scale", "shell", "bone", "horn", "tooth",
    "claw", "fang", "hoof", "paw", "wing", "tail", "fin", "tentacle", "whisker", "antenna",
    "proboscis", "stinger", "sucker", "hook", "barb", "spike", "thorn", "leaf", "petal", "seed",
    "fruit", "vegetable", "herb", "spice", "mushroom", "fungus", "lichen", "algae", "bacteria",
    "fungi", "mold", "yeast", "virus", "parasite", "prion", "microbe", "germ", "pathogen",
    "bacterium", "archaea", "protozoan", "alga", "fungus", "mushroom", "lichen", "yeast", "microorganism",
    "cell", "organism", "species", "genus", "family", "order", "class", "phylum", "kingdom",
    "domain", "life form", "creature", "being", "entity", "organism", "microorganism",
    "bacterium", "archaeon", "protozoan", "alga", "fungus", "mushroom", "lichen", "yeast", 
    "meat-wall", "flesh", "muscle", "skin", "bone", "cartilage", "tendon", "ligament",
    "organ", "organ system", "nervous system", "circulatory system", "respiratory system",
    "digestive system", "machine-man", "time machine", "jetpack", "hoverboard",
    "teleporter", "cloning device", "hologram projector", "force field", "energy shield",
    "gravity manipulator", "matter replicator", "nanobot swarm", "robotic arm",
    "cybernetic implant", "exoskeleton", "power armor", "mech suit", "battle suit",
    "stealth suit", "space suit", "hazmat suit", "environment suit", "combat armor",
    "riot gear", "tactical vest", "utility belt", "backpack", "satchel", "messenger bag",
    "duffel bag", "briefcase", "toolbox", "first aid kit", "survival kit", "emergency kit",
    "fishing gear", "hunting gear", "camping gear", "climbing gear", "scuba gear",
    "yacht", "boat", "ship", "submarine", "airplane", "helicopter", "drone",
    "spaceship", "rocket", "satellite", "space station", "moon rover", "mars rover",
    "robot", "android", "cyborg", "automaton", "golem", "mecha", "exosuit", "drone",
    "puppet", "marionette", "animatronic", "robotic pet", "robotic companion",
    "mystery", "puzzle box", "treasure map", "ancient scroll", "magic tome",
    "spellbook", "alchemical formula", "ritual guide", "prophecy", "legend", "myth",
    "junkyard creation", "scrap metal sculpture", "found object art", "upcycled creation",
    "recycled art", "repurposed object", "assemblage art", "collage", "clockwork device",
    "mechanical contraption", "steampunk gadget", "retro-futuristic device",
    "cybernetic enhancement", "biomechanical implant", "nanotechnology", "genetic modification",
    "cloning technology", "artificial intelligence", "virtual reality headset", "augmented reality glasses",
    "holographic display",   
    "virus", "parasite", "prion", "cell", "tissue", "organ", "system", "body", "creature",
    "grandmother", "grandfather", "mother", "father", "sister", "brother", "aunt", "uncle",
    "cousin", "niece", "nephew", "son", "daughter", "child", "baby", "infant", "toddler",
    "teenager", "adult", "elderly", "ancestor", "descendant", "relative", "family", "teddy bear",
    "plushie", "stuffed toy", "action figure", "figurine", "model kit", "dollhouse", "playset",
    "doll", "action figure", "stuffed animal", "toy", "game piece", "puzzle piece", "collectible",
    "figurine", "model", "replica", "souvenir", "keepsake", "memento", "gift", "present",
    "pirate ship", "treasure chest", "magic wand", "crystal ball", "spellbook",
    "potion bottle", "scroll", "map", "compass", "key", "locket", "crown", "scepter", "orb",
    "staff", "sword", "dagger", "axe", "bow", "crossbow", "shield", "armor", "helmet", "boots",
    "gloves", "cloak", "robe", "mask", "amulet", "ring", "necklace", "bracelet", "earrings",
    "offering", "tribute", "sacrifice", "reward", "prize", "medal", "trophy", "certificate",
    "diploma", "degree", "license", "permit", "contract", "agreement", "document", "record",
    "file", "folder", "notebook", "journal", "diary", "planner", "schedule", "map", "blueprint",
    "arms", "pistol", "rifle", "shotgun", "machine gun", "sniper rifle", "rocket launcher",
    "grenade", "missile", "bomb", "mine", "trap", "explosive", "flamethrower", "crossbow",
    "sling", "catapult", "ballista", "harpoon", "lance", "javelin", "spear gun", "boomerang",
    "whip", "chain", "flail", "mace", "club", "staff", "wand", "scepter", "cane", "baton",
    "trident", "halberd", "polearm", "scythe", "sickle", "swordfish", "rapier", "foil", "sabers",
    "cutlass", "broadsword", "katana", "nunchaku", "tonfa", "shuriken", "throwing star",
    "dart", "boomerang", "blowgun", "slingshot", "bow and arrow", "crossbow", "sling", "harpoon",
    "lance", "javelin", "spear", "trident", "halberd", "poleaxe", "battle axe", "war hammer",
    "mace", "flail", "morning star", "cestus", "knuckle duster", "brass knuckles", "claws",
    "fangs", "stinger", "horns", "spikes", "blades", "razor", "scissors", "shears", "knife",
    "dagger", "dirk", "stiletto", "shiv", "switchblade", "butterfly knife", "hunting knife",
    "survival knife", "utility knife", "kitchen knife", "chef's knife", "paring knife",
    "carving knife", "bread knife", "cleaver", "boning knife", "fillet knife", "steak knife",
    "scalpel", "surgical knife", "box cutter", "razor blade", "letter opener", "paper cutter",
    "sword", "katana", "rapier", "foil", "saber", "broadsword", "longsword", "shortsword",
    "greatsword", "claymore", "zweihander", "scimitar", "falchion", "gladius", "spatha",
    "cutlass", "machete", "bolo knife", "kukri", "parang", "panga", "bolo", "shark",
    "swordfish", "saber-toothed tiger", "raptor", "triceratops", "tyrannosaurus rex",
    "velociraptor", "pterodactyl", "brontosaurus", "stegosaurus", "ankylosaurus", "spinosaurus",
    "diplodocus", "alligator", "crocodile", "komodo dragon", "iguana", "chameleon", "gecko",
    "monitor lizard", "gila monster", "frilled lizard", "bearded dragon", "flying lizard",
    "fossil", "bone", "skull", "teeth", "claws", "scales", "shell", "carapace", "exoskeleton",
    "feathers", "fur", "hair", "whiskers", "antennae", "wings", "tail", "fin", "tentacle",
    "stinger", "sucker", "hook", "barb", "spike", "thorn", "leaf", "petal", "seed", "fruit",
    "vegetable", "herb", "spice", "mushroom", "fungus", "lichen", "algae", "bacteria", "virus",
    "parasite", "prion", "cell", "tissue", "organ", "system", "body", "creature", "animal",
    "beast", "monster", "mythical creature", "legendary beast", "fantastical being", "supernatural entity",
    "paranormal phenomenon", "occult symbol", "esoteric knowledge", "arcane ritual", "mystic artifact",
    "spiritual totem", "divine relic", "holy symbol", "sacred text", "profane object", "blessed charm",
    "cursed talisman", "enchanted amulet", "bewitched ring", "Hercules", "Thor", "Zeus", "Poseidon",
    "leg", "arm", "hand", "foot", "head", "torso", "chest", "back", "stomach", "waist",
    "shoulder", "elbow", "knee", "ankle", "wrist", "finger", "toe", "neck", "face", "eye",
    "ear", "nose", "mouth", "lip", "tongue", "tooth", "hair", "beard", "mustache", "eyebrow",
    "eyelash", "cheek", "chin", "forehead", "jaw", "skull", "brain", "heart", "lung",
    "liver", "kidney", "stomach", "intestine", "bladder", "pancreas", "spleen", "gallbladder",
    "appendix", "skin", "muscle", "bone", "cartilage", "tendon", "ligament", "nail", "cuticle",
    "pupil", "iris", "cornea", "retina", "optic nerve", "ear canal", "eardrum", "auditory nerve",
    "vocal cords", "larynx", "trachea", "esophagus", "diaphragm", "ribcage", "spine", "vertebrae",
    "pelvis", "hip", "femur", "tibia", "fibula", "patella", "radius", "ulna", "carpal bones",
    "metacarpal bones", "phalanges", "tarsal bones", "metatarsal bones", "calcaneus", "talus",
    "navicular", "cuboid", "cuneiform bones", "scapula", "clavicle", "sternum", "costal cartilage",
    "sacrum", "coccyx", "humerus", "scaphoid", "lunate", "triquetrum", "pisiform", "trapezium",
    "trapezoid", "capitate", "hamate", "metacarpals", "phalanges", "metatarsals", "tarsals",
    "cooking utensil", "kitchen tool", "household item", "furniture", "appliance", "decoration",
    "accessory", "gadget", "device", "electronic", "musical instrument", "magic item",
    "weapon", "tool", "utensil", "cutlery", "kitchenware", "appliance", "gun", "blade", "spear",
    "axe", "hammer", "saw", "drill", "wrench", "screwdriver", "pliers", "tongs", "shovel",
    "rake", "hoe", "spade", "pickaxe", "crowbar", "sledgehammer", "mallet", "chisel", "file",
    "sandpaper", "paintbrush", "roller", "spray can", "marker", "pen", "pencil", "crayon",
    "chalk", "eraser", "highlighter", "glue", "tape", "stapler", "scissors", "knife", "fork",
    "spoon", "ladle", "whisk", "peeler", "grater", "zester", "mortar and pestle", "colander",
    "strainer", "sifter", "measuring cup", "measuring spoon", "scale", "timer", "thermometer",
    "oven", "stove", "microwave", "toaster", "blender", "food processor", "coffee maker",
    "kettle", "teapot", "cooker", "slow cooker", "pressure cooker", "rice cooker", "grill",
    "barbecue", "smoker", "deep fryer", "air fryer", "ice cream maker", "popcorn maker",
    "bread maker", "juicer", "citrus juicer", "wine opener", "bottle opener", "can opener",
    "corkscrew", "peanut butter jar", "spice rack", "salt shaker", "pepper mill", "condiment bottle",
    "ketchup bottle", "mustard jar", "mayonnaise jar", "saucepan", "frying pan", "baking dish",
    "cookie sheet", "roasting pan", "casserole dish", "pie dish", "cake pan", "muffin tin",
    "loaf pan", "springform pan", "pizza stone", "griddle", "waffle iron", "pancake griddle",
    "crepe pan", "tortilla press", "pasta maker", "ice cream scoop", "cookie cutter", "rolling pin",
    "pastry brush", "basting brush", "meat tenderizer", "pizza cutter", "cheese grater",
    "cheese slicer", "egg separator", "egg timer", "egg poacher", "egg whisk", "egg beater",
    "egg slicer", "egg holder", "egg cup", "egg carton", "egg crate", "egg basket", "egg tray",
    "egg separator", "egg timer", "egg poacher", "egg whisk", "egg beater", "egg slicer",
    "furniture", "fixture", "decoration", "accessory", "gadget", "device", "electronic", "musical instrument"
    "magic," "music", "war", "healing", "divination", "science", "art", "communication",
    "transportation", "construction", "destruction", "exploration", "survival", "agriculture",
    "industry", "trade", "education", "entertainment", "religion", "government", "law", "justice",
    "medicine", "psychology", "philosophy", "history", "sociology", "anthropology", "archaeology",
    "linguistics", "dance", "cooking", "baking", "crafting", "building", "repairing", "inventing",
    "designing", "programming", "coding", "hacking", "gaming", "streaming", "vlogging", "blogging",
    "podcasting", "photography", "filmmaking", "acting", "directing", "producing", "writing",
    "editing", "animating", "illustrating", "drawing", "painting", "sculpting", "crafting",
    "sewing", "knitting", "crocheting", "embroidery", "quilting", "weaving", "pottery", "ceramics",
    "glassblowing", "woodworking", "metalworking", "leatherworking", "jewelry making", "upcycling",
    "recycling", "gardening", "landscaping", "farming", "forestry", "hunting", "fishing", "foraging",
    "cooking", "baking", "brewing", "fermenting", "pickling", "canning", "preserving", "smoking",
    "curing", "drying", "salting", "spicing", "seasoning", "marinating", "grilling", "roasting",
    "steaming", "boiling", "frying", "sautéing", "baking", "broiling", "toasting", "blanching",
    "poaching", "stewing", "braising", "cooking", "baking", "grilling", "roasting", "frying",
    "steaming", "boiling", "sautéing", "blanching", "poaching", "braising", "stewing", "canning",
    "chart", "graph", "table", "list", "inventory", "log", "ledger", "receipt", "ticket",
    "pass", "voucher", "coupon", "menu", "recipe", "instruction manual", "guidebook", "handbook",
    "textbook", "workbook", "study guide", "reference book", "dictionary", "thesaurus",
    "encyclopedia", "atlas", "glossary", "index", "catalog", "directory", "dinosaur",
    "tyrannosaurus rex", "triceratops", "velociraptor", "brachiosaurus", "stegosaurus", "spinosaurus",
    "ankylosaurus", "diplodocus", "pterodactyl", "ichthyosaur", "mosasaur", "plesiosaur",
    "sauropod", "carnivore", "herbivore", "omnivore", "insect", "arachnid", "crustacean",
    "mollusk", "cephalopod", "gastropod", "bivalve", "barnacle", "lobster", "crab", "shrimp",
    "octopus", "squid", "snail", "slug", "worm", "leech", "fly", "bee", "ant", "butterfly",
    "moth", "beetle", "cockroach", "grasshopper", "cricket", "locust", "dragonfly", "damselfly",
    "firefly", "lightning bug", "mosquito", "gnat", "tick", "flea", "louse", "mite", "spider",
    "scorpion", "tarantula", "wolf spider", "orb-weaver", "jumping spider", "black widow",
    "brown recluse", "daddy longlegs", "crab spider", "trapdoor spider", "silkworm", "caterpillar",
    "pupa", "chrysalis", "larva", "nymph", "adult", "queen bee", "worker bee", "drone", "honeycomb",
    "beehive", "apiary", "nectar", "pollen", "hive", "swarm", "colony", "nest", "burrow", "den",
    "lair", "cave", "hole", "pit", "grotto", "canyon", "valley", "mountain range", "tower",
    "fort", "bunker", "outpost", "watchtower", "keep", "stronghold", "citadel", "bastion",
    "castle", "fortress", "palace", "temple", "shrine", "church", "mosque", "synagogue",
    "pagoda", "monastery", "abbey", "convent", "cathedral", "chapel", "basilica", "crypt",
    "mausoleum", "tomb", "grave", "memorial", "monument", "statue", "sculpture", "fountain",
    "waterfall", "spring", "river", "lake", "pond", "ocean", "sea", "bay", "gulf", "fjord",
    "harbor", "port", "dock", "pier", "beach", "shore", "coast", "cliff", "bluff", "hill",
    "mountain", "peak", "summit", "ridge", "valley", "plain", "prairie", "savannah", "steppe",
    "desert", "oasis", "canyon", "gorge", "ravine", "creek", "stream", "brook", "spring",
    "waterfall", "geyser", "hot spring", "mud pool", "lava flow", "volcano", "earthquake",
    "tsunami", "hurricane", "tornado", "cyclone", "storm", "blizzard", "snowstorm", "rainstorm",
    "thunderstorm", "lightning storm", "sandstorm", "dust storm", "fog", "mist", "haze",
    "smog", "cloud", "sky", "sun", "moon", "star", "planet", "galaxy", "universe", "cosmos",
    "nebula", "black hole", "supernova", "asteroid", "comet", "meteor", "meteorite", "satellite",
    "spacecraft", "rocket", "shuttle", "probe", "lander", "rover", "station", "outpost",
    "colony", "habitat", "base", "research facility", "laboratory", "observatory", "teleportation pad",
    "portal", "gateway", "bridge", "tunnel", "highway", "road", "path", "trail", "track",
    "street", "avenue", "boulevard", "lane", "alley", "driveway", "parking lot", "garage",
    "car", "truck", "bus", "motorcycle", "bicycle", "scooter", "skateboard", "rollerblades",
    "hoverboard", "segway", "carriage", "wagon", "boat", "ship", "submarine", "yacht",
    "canoe", "kayak", "raft", "sailboat", "fishing boat", "speedboat", "cruise ship",
    "airplane", "helicopter", "glider", "hot air balloon", "blimp", "jetpack", "parachute",
    "hang glider", "kite", "ufo", "spaceship", "starship", "galactic cruiser", "interstellar ship",
    "warp ship", "teleportation device", "time machine", "dimensional portal", "magic carpet",
    "flying broomstick", "levitating platform", "hovercraft", "magnetic levitation train",
    "monorail", "bullet train", "steam locomotive", "diesel locomotive", "electric locomotive",
    "cable car", "funicular", "tram", "trolley", "streetcar", "light rail", "subway", "metro",
    "underground", "elevator", "escalator", "staircase", "ladder", "rope bridge", "suspension bridge",
    "cable-stayed bridge", "drawbridge", "bascule bridge", "swing bridge", "lift bridge",
    "arch bridge", "beam bridge", "truss bridge", "cantilever bridge", "covered bridge",
    "drawbridge", "swing bridge", "lift bridge", "toll bridge", "footbridge", "pedestrian bridge",
    "zip line", "bungee cord", "paragliding harness", "rock climbing gear", "hiking boots",
    "camping gear", "backpack", "tent", "sleeping bag", "flashlight", "compass", "map",
    "first aid kit", "survival kit", "water bottle", "food rations", "firestarter", "matches",
    "lighter", "multitool", "knife", "axe", "saw", "shovel", "pickaxe", "crowbar", "hammer",
    "screwdriver", "wrench", "pliers", "socket set", "ratchet", "level", "tape measure",
    "caliper", "square", "chalk line", "stud finder", "drill", "sander", "grinder", "welder",
    "torch", "lantern", "candle", "oil lamp", "fire pit", "barbecue grill", "smoker",
    "campfire", "stove", "oven", "microwave", "toaster", "blender", "food processor",
    "coffee maker", "tea kettle", "water purifier", "ice maker", "refrigerator", "freezer",
    "dishwasher", "washing machine", "dryer", "iron", "ironing board", "vacuum cleaner",
    "mop", "broom", "dustpan", "sponge", "bucket", "cleaning supplies", "laundry detergent",
    "dish soap", "hand soap", "shampoo", "conditioner", "body wash", "toothpaste", "toothbrush",
    "razor", "shaving cream", "deodorant", "perfume", "cologne", "lotion", "sunscreen", "lip balm",
    "hand sanitizer", "first aid ointment", "bandages", "pain reliever", "cold medicine",
    "allergy medication", "vitamins", "supplements", "health supplements", "protein powder",
    "energy drink", "sports drink", "water", "juice", "soda", "tea", "coffee", "milk", "beer", "wine",
    "spirits", "liquor", "cocktail", "mocktail", "smoothie", "milkshake", "iced tea", "lemonade", "hot chocolate",
    "water substitute", "Doomguy", "Master Chief", "Link", "Zelda", "Mario", "Luigi", "Peach", "Bowser",
    "Donkey Kong", "Samus Aran", "Kirby", "Fox McCloud", "Pikachu", "Sonic the Hedgehog", "Megaman",
    "Ryu", "Chun-Li", "Sub-Zero", "Scorpion", "Lara Croft", "Nathan Drake", "Indiana Jones", "James Bond",
    "Gordon Freeman", "Cloud Strife", "Sephiroth", "Tifa Lockhart", "Aerith Gainsborough", "Yuffie Kisaragi",
    "Vincent Valentine", "Red XIII", "Barret Wallace", "Cait Sith", "Cid Highwind", "Ragnar Lothbrok",
    "Conan the Barbarian", "Beowulf", "King Arthur", "Robin Hood", "Sherlock Holmes", "Hercule Poirot",
    "Miss Marple", "James T. Kirk", "Spock", "Jean-Luc Picard", "Street Fighter character", "rockstar",
    "pop star", "movie star", "television star", "comedian", "actor", "actress", "director", "movie",
    "television show", "web series", "documentary", "anime", "manga", "graphic novel", "comic book",
    "webcomic", "podcast", "radio show", "music album", "song", "music video", "art exhibition",
    "art installation", "sculpture", "painting", "drawing", "photography", "digital art", "street art",
    "theater performance", "dance recital", "circus act", "magic show", "stand-up comedy", "elephant",
    "lion", "tiger", "bear", "wolf", "fox", "rabbit", "deer", "moose", "elk", "bison", "buffalo",
    "giraffe", "zebra", "hippopotamus", "rhinoceros", "camel", "llama", "alpaca", "donkey",
    "horse", "pony", "mule", "zebu", "yak", "water buffalo", "caribou", "reindeer", "antelope",
    "gazelle", "impala", "springbok", "wildebeest", "gnu", "okapi", "aardvark", "armadillo",
    "pangolin", "skunk", "badger", "weasel", "otter", "beaver", "mink", "ferret", "stoat",
    "ermine", "sable", "martin", "wolverine", "hyena", "jackal", "coyote", "dingo", "wild dog",
    "foxhound", "bloodhound", "beagle", "bulldog", "boxer", "poodle", "collie", "shepherd",
    "retriever", "spaniel", "terrier", "chihuahua", "pug", "bearded dragon", "iguana", "gecko",
    "chameleon", "snake", "python", "cobra", "viper", "lizard", "tortoise", "turtle", "frog",
    "toad", "newt", "salamander", "axolotl", "fish", "shark", "whale", "dolphin", "porpoise",
    "octopus", "squid", "jellyfish", "starfish", "seahorse", "crab", "lobster", "shrimp",
    "barnacle", "clam", "oyster", "mussel", "scallop", "snail", "slug", "worm", "leech",
    "insect", "bee", "wasp", "hornet", "ant", "butterfly", "moth", "beetle", "cockroach",
    "grasshopper", "cricket", "locust", "dragonfly", "damselfly", "firefly", "lightning bug",
    "Charmander", "Squirtle", "Bulbasaur", "Pikachu", "Eevee", "Jigglypuff", "Meowth", "Mewtwo",
    "Gengar", "Charizard", "Blastoise", "Venusaur", "Snorlax", "Lapras", "Articuno", "Zapdos",
    "Moltres", "Dratini", "Dragonair", "Dragonite", "Mew", "Celebi", "Jirachi", "Deoxys",
    "Phione", "phone", "computer", "tablet", "smartphone", "laptop", "desktop", "server", "mainframe",
    "supercomputer", "quantum computer", "robot", "android", "cyborg", "humanoid", "automaton",
    "golem", "homunculus", "puppet", "marionette", "animatronic", "doll", "action figure",
    "plush toy", "stuffed animal", "figurine", "model kit", "statue", "bust", "carving",
    "statue", "sculpture", "relief", "engraving", "etching", "mosaic", "fresco", "painting",
    "drawing", "sketch", "illustration", "comic strip", "graphic novel", "webcomic", "cartoon",
    "figurine", "statue", "sculpture", "bust", "relief", "carving", "engraving", "etching",
    "mosaic", "fresco", "painting", "drawing", "sketch", "illustration", "comic strip",
    "graphic novel", "webcomic", "cartoon", "anime", "manga", "video game", "board game",
    "card game", "role-playing game", "tabletop game", "strategy game", "puzzle game",
    "adventure game", "action game", "shooter", "platformer", "racing game", "sports game",
    "simulation game", "sandbox game", "open-world game", "survival game", "horror game",
    "stealth game", "puzzle-platformer", "metroidvania", "roguelike", "battle royale",
    "karate attack", "heist", "expensive dinner", "axe", "sword", "dagger", "knife",
    "spear", "lance", "halberd", "polearm", "staff", "wand", "rod", "crossbow", "bow",
    "arrow", "bolt", "quiver", "shield", "armor", "helmet", "gauntlet", "greaves", "boots",
    "cloak", "robe", "tunic", "dress", "skirt", "pants", "shorts", "shirt", "blouse",
    "sweater", "jacket", "coat", "cape", "scarf", "hat", "cap", "beanie", "headband",
    "bandana", "mask", "goggles", "sunglasses", "gloves", "mittens", "belt", "sash",
    "pouch", "satchel", "backpack", "bag", "saddle", "harness", "leash", "collar",
    "harness", "whip", "rope", "chain", "cable", "wire", "cord", "string", "thread",
    "yarn", "fishing line", "wireless connection", "Bluetooth", "Wi-Fi", "cellular network",
    "satellite", "radio", "television", "internet", "streaming service", "social media",
    "website", "blog", "forum", "chat room", "message board", "email", "text message",
    "Hotline Miami character", "biker", "gangster", "hitman", "spy", "secret agent", "god",
    "demigod", "mythological figure", "legendary hero", "fabled creature", "superhero",
    "villain", "anti-hero", "protagonist", "antagonist", "supporting character", "minor character",
    "background character", "extra", "cameo appearance", "narrator", "guide", "mentor", "mascot",
    "side character", "love interest", "rival", "nemesis", "friend", "foe", "enemy", "final boss of the game",
    "main antagonist", "main protagonist", "plot twist character", "red herring", "comic relief",
    "tragic hero", "flawed hero", "reluctant hero", "hero's journey", "quest giver", "treasure hunter",
    "artifact seeker", "monster hunter", "ghostbuster", "vampire slayer", "werewolf hunter",
    "zombie apocalypse survivor", "alien invader", "android", "cyborg", "clone", 
    "hologram", "AI", "sentient being", "consciousness", "entity", "specter", "phantom",
    "illusion", "mirage", "vision", "dream", "nightmare", "memory", "hallucination", "delusion",
    "fantasy", "reality", "simulation", "virtual reality", "augmented reality", "parallel universe",
    "astronaut", "cosmonaut", "space explorer", "interstellar traveler", "galactic adventurer",
    "brother from another mother", "best friend", "partner in crime", "dynamic duo", "trio",
    "quartet", "team", "squad", "crew", "gang", "clique", "circle of friends", "alliance",
    "fellowship", "brotherhood", "sisterhood", "coven", "guild", "order", "society", "cult",
    "planet", "star system", "galaxy", "universe", "dimension", "realm", "plane of existence",
    "mythical realm", "enchanted forest", "forbidden land", "hidden world", "lost city",
    "ancient ruins", "forgotten temple", "mystical island", "cursed graveyard", "haunted mansion",
    "abandoned castle", "deserted village", "forgotten battlefield", "enchanted garden",
    "magical spring", "mystic cave", "hidden grotto", "secret passage", "ancient library",
    "forgotten archive", "mystical observatory", "enchanted tower", "hidden chamber",
    "secret room", "panic room", "Santa Claus", "Easter Bunny", "Tooth Fairy", "Sandman",
    "Jack Frost", "Grinch", "Krampus", "Cupid", "leprechaun", "banshee", "witch", "warlock",
    "political cartoon lacking in any subtlety at all", "satirical character", "parody",
    "spoof", "caricature", "lampoon", "mockery", "satire", "irony", "humor", "comedy",
    "man who shouldn't be where he is", "unusual guest", "unexpected visitor", "intruder",
    "unexpected ally", "surprise antagonist", "mysterious stranger", "enigmatic figure",
    "masked hero", "secret identity", "hidden persona", "alter ego", "double life",
    "masked vigilante", "cloaked figure", "hooded stranger", "faceless entity", "nameless being",
    "unknown traveler", "lost soul", "wandering spirit", "roaming ghost", "drifting entity",
    "aimless wanderer", "seeker of truth", "quest for knowledge", "journey of discovery",
    "robot who gets horny when he get electrocuted", "professional bowler", "world-class chef",
    "expert gardener", "master carpenter", "skilled blacksmith", "talented musician",
    "gifted artist", "proficient coder", "adept hacker", "seasoned detective", "experienced pilot",
    "veteran soldier", "battle-hardened warrior", "seasoned adventurer", "skilled negotiator",
    "persuasive diplomat", "charismatic leader", "inspiring figure", "visionary", "innovator",
    "trailblazer", "pioneer", "groundbreaker", "pathfinder", "trendsetter", "rule-breaker",
    "boundary-pusher", "convention-defier", "status quo challenger", "game-changer",
    "disruptor", "revolutionary", "radical thinker", "out-of-the-box thinker", "creative genius",
    "problem solver", "critical thinker", "strategic planner", "tactical genius", "mastermind",
    "grand strategist", "chess master", "game theorist", "decision maker", "risk taker",
    "opportunity seeker", "fortune hunter", "adventure seeker", "thrill seeker", "daredevil",
    "Daredevil", "Ironman", "tuna fish", "swordfish", "shark", "whale", "octopus", "squid",
    "jellyfish", "starfish", "seahorse", "crab", "lobster", "shrimp", "barnacle", "clam",
    # Whimsical objects
    "rubber duck", "singing teapot", "dancing broom", "enchanted umbrella", "clockwork mouse",
    "flying book", "invisible hat", "self-writing quill", "bottomless bag", "mystery box",
    "pocket dimension", "rainbow scarf", "moon cheese", "star lantern", "cloud in a jar",
    "time-traveling pocket watch", "gravity-defying boots", "self-replenishing ink",
    "magical compass", "whimsical wind-up toy", "enchanted mirror", "talking painting",
    "living statue", "singing crystal", "dancing candle", "floating feather", "enchanted key",
    "self-folding origami", "magical snow globe", "whispering seashell", "laughing teacup",
    "time-turning hourglass", "perpetual motion machine", "impossible cube", "Escher staircase",
    "levitating globe", "self-playing piano", "singing violin", "dancing marionette",
    "whimsical wind chimes", "enchanted lantern", "floating island", "talking book",
    "self-watering plant", "magical paintbrush", "living tapestry", "enchanted quill",
    "mirror maze", "infinite bookshelf", "talking mirror", "sentient sandwich", "sassy cactus",
    "jellybean tree", "bubble pipe", "singing sword", "laughing lantern",
    "mood ring that changes the weather", "umbrella that rains indoors",
    "boots that walk themselves", "hat that tells jokes", "puzzle box that solves itself",
    "magical paintbrush", "self-stirring cauldron", "enchanted compass", "whimsical wind chimes",
    "floating teacup", "dancing teapot", "singing kettle", "whistling kettle", "talking teapot",
    "enchanted teacup", "magical teapot", "flying teapot", "self-filling teapot", "time-traveling teapot",
    # Mythological beings
    "kitsune", "baku", "tengu", "wendigo", "selkie", "banshee", "kelpie", "nuckelavee",
    "yokai", "yurei", "kappa", "tanuki", "rokurokubi", "shōjō", "shōki", "yama-uba",
    "yeti", "sasquatch", "bigfoot", "chupacabra", "loch ness monster", "kraken", "leviathan",
    "gorgon", "sphinx", "chimera", "minotaur", "centaur", "satyr", "nymph", "dryad",
    "siren", "mermaid", "vampire", "werewolf", "zombie", "ghost", "poltergeist", "demon",
    "angel", "archangel", "fallen angel", "djinn", "genie", "golem", "elemental",
    "djinni", "naga", "garuda", "rakshasa", "asura", "rakshasi", "vritra", "basilisk",
    "cockatrice", "hydra", "cerberus", "griffin", "pegasus", "phoenix", "unicorn",
    "pegasus", "manticore", "basilisk", "cyclops", "gargoyle", "salamander", "dryad",
    "faun", "satyr", "leprechaun", "fairy", "pixie", "sprite", "brownie", "gnome", "dwarf",
    "troll", "ogre", "goblin", "hobgoblin", "bugbear", "gremlin", "imp", "succubus",
    "incubus", "wraith", "specter", "phantom", "shade", "poltergeist", "revenant",
    "chupacabra", "mokele-mbembe", "yeti", "sasquatch", "jackalope", "mothman", "krampus",
    "baba yaga", "leshy", "domovoi", "zashiki-warashi", "oni", "naga", "garuda", "roc",
    "ifrit", "djinn", "troll under the bridge", "will-o'-the-wisp", "fae courtier",
    "dream eater", "nightmare steed", "phoenix egg", "unicorn horn", "griffin feather",
    "mermaid's comb", "dragon scale", "goblin king's crown", "minotaur's labyrinth map",
    "siren's song", "vampire's fang", "werewolf's claw", "zombie's brain", "ghost's chain",
    "angel's feather", "demon's horn", "golem's heart", "centaur's bow", "sphinx's riddle",
    "hydra's head", "chimera's tail", "basilisk's gaze", "cyclops' eye", "cerberus' collar",
    "pegasus' wing", "griffin's talon", "phoenix's ashes", "dragon's breath", "kraken's tentacle",
    # Modern tech
    "quantum laptop", "AI assistant", "holographic phone", "smart glasses",
    "wearable translator", "solar-powered skateboard", "drone delivery box",
    "robotic pet", "3D-printed pizza", "virtual reality headset",
    "augmented reality glasses", "self-driving car", "nanobot swarm",
    "bioengineered plant", "smart fridge", "voice-activated lamp", "wireless charger mat",
    "modular smartwatch", "digital paintbrush", "cloud storage crystal",
    "encrypted USB amulet", "cybernetic arm", "bionic eye", "neural link headband",
    "memory chip earring", "solar backpack", "gravity boots", "maglev scooter",
    "smart home hub", "biometric lockbox", "quantum key", "haptic feedback suit",
    "teleportation device", "time dilation watch", "dimensional rift generator",
    "antimatter battery", "dark matter stabilizer", "wormhole communicator",
    "plasma cutter", "laser engraver", "fusion reactor core", "cryogenic chamber",
    "particle accelerator", "gravity well projector", "black hole generator",
    "time machine", "dimensional portal", "antigravity belt", "telekinesis glove",
    "cloaking device", "force field generator", "repulsor ray", "plasma rifle",
    "energy shield", "sonic disruptor", "EMP grenade", "holographic projector",
    "nanite swarm", "biometric scanner", "smart dust", "quantum entanglement communicator",
    "neural interface", "augmented reality contact lenses", "smart fabric",
    "self-repairing material", "programmable matter", "adaptive camouflage suit",
    "smart dust", "quantum computer", "neural network", "machine learning algorithm",
    "blockchain ledger", "cryptocurrency wallet", "augmented reality interface",
    # Visually distinct pop culture objects
    "magical ring", "Chaos Emerald", "Mjolnir", "Infinity Gauntlet", "Batarang", "Web Shooter",
    "Lightsaber", "Gundam", "Poké Ball terrarium", "Master Sword", "Triforce", "Dragon Balls",
    "TARDIS", "DeLorean", "Portal Gun", "PokeDex", "Poké Ball", "Blades of Chaos",
    "Starship Enterprise", "Power Star", "Fire Flower", "Yoshi Egg", "Animal Crossing fossil",
    "Katamari ball"
}

verbs = {
    "fight", "befriend", "discover", "build", "destroy", "paint", "draw", "find", "lose", "rescue",
    "challenge", "teache", "learn", "transform", "runs from", "chases", "protects", "steals from",
    "help", "meet", "greet", "avoid", "explore", "studie", "adopt", "name", "feed", "capture",
    "escapes from", "dreams of", "remembers", "forgets", "searches for", "hides from", "reveals", "summons", "banishes",
    "enchant", "curse", "bless", "question", "answer", "warn", "invite", "join", "lead", "follow", "watche",
    "ignore", "celebrate", "mourn", "create", "destroy", "fixe", "break", "throw", "catche", "ride", "flies with",
    "swims with", "climb", "descend", "ascend", "travel", "compete", "cooperate", "argue",
    "negotiate", "trade", "share", "compare", "contrast", "contradict", "support",
    "oppose", "challenge", "debate", "discusse", "analyze", "evaluate", "criticize", "praise", "consider",
    "examine", "investigate", "researche", "studie", "observe", "monitor", "survey", "inspect", "predict",
    "forecast", "project", "plan", "strategize", "organize", "coordinate", "manage", "direct", "explain",
    "describe", "illustrate", "demonstrate", "show", "tell", "narrate", "relate", "recall", "remember", "watche",
    "listens to", "hear", "see", "feel", "smell", "taste", "touche", "sense", "perceive", "experience", "understand",
    "comprehend", "grasp", "apprehend", "realize", "recognize", "acknowledge", "accept", "reject", "endorse", "support",
    "oppose", "resist", "fight", "stand", "defend", "attack", "assault", "ambush", "surprise",
    "sneak", "train", "practice", "exorcise", "hunt", "capture", "pursue", "follow", "chase",
    "navigate", "explore", "discover", "uncover", "reveal", "expose", "unveil", "unearth", "unfold", "unravel",
    "unlock", "unseal", "uncloak", "unmask", "unveil", "unfold", "unravel", "unlock", "unseal", "uncloak",
    "unmask", "unveil", "unfold", "unravel", "unlock", "unseal", "uncloak", "unmask", "unveil", "unfold",
    "rig", "hack", "crack", "break", "infiltrate", "spy", "eavesdrop", "surveil", "monitor", "observe",
    "analyze", "investigate", "research", "study", "examine", "inspect", "test", "experiment",
    "evaluate", "assess", "measure", "quantify", "qualify", "classify", "categorize", "label", "tag",
    "organize", "arrange", "sort", "group", "cluster", "bundle", "package", "wrap", "seal", "box", "crate", "file",
    "document", "record", "log", "journal", "archive", "catalog", "inventory", "register", "list", "enumerate",
    "count", "tally", "total", "sum", "calculate", "compute", "estimate", "approximate", "project",
    "forecast", "predict", "anticipate", "prepare", "plan", "strategize", "organize", "coordinate",
    "manage", "direct", "lead", "supervise", "oversee", "control", "command", "govern", "rule",
    "administer", "execute", "implement", "enforce", "apply", "utilize", "use", "employ", "deploy", "leverage",
    "exploit", "capitalize", "maximize", "optimize", "streamline", "simplify", "enhance", "improve",
    "upgrade", "update", "refine", "polish", "perfect", "master", "excel", "succeed", "achieve",
    "accomplish", "attain", "realize", "fulfill", "satisfy", "meet", "exceed", "surpass", "outperform",
    "outshine", "outclass", "outdo", "outmatch", "outstrip", "outpace", "outlast", "outwit",
    "outsmart", "outmaneuver", "outplay", "outthink", "outmaneuver", "outfox", "outwit", "outsmart",
    "participate", "engage", "involve", "include", "invite", "welcome", "embrace", "adopt", "hurt",
    "heal", "cure", "treat", "care for", "nurture", "raise", "gather", "collect", "assemble", "construct",
    "build", "create", "design", "invent", "innovate", "develop", "engineer", "fabricate", "manufacture",
    "produce", "synthesize", "compose", "write", "compose", "orchestrate", "arrange", "score", "perform",
    "play", "sing", "dance", "act", "direct", "film", "shoot", "edit", "produce", "broadcast", "stream", "record",
    "publish", "distribute", "share", "promote", "advertise", "market", "sell", "trade", "barter", "exchange",
    "gift", "donate", "contribute", "support", "sponsor", "fund", "invest", "finance", "back", "endorse", "champion",
    "advocate", "defend", "protect", "educate", "teach", "mentor", "coach", "guide", "lead", "inspire", "motivate",
    "encourage", "empower", "uplift", "enlighten", "illuminate", "inform", "enrich", "expand", "broaden",
    "deepen", "widen", "strengthen", "fortify", "reinforce", "bolster", "support", "sustain", "nurture",
    "cultivate", "foster", "nourish", "cherish", "treasure", "value", "appreciate", "respect", "honor",
    "admire", "esteem", "regard", "venerate", "worship", "revere", "idolize", "glorify", "celebrate",
    "commemorate", "memorialize", "remember", "reflect", "contemplate", "ponder", "meditate", "ruminate",
    "muse", "speculate", "theorize", "hypothesize", "postulate", "conjecture", "infer", "deduce",
    "induce", "reason", "logic", "analyze", "synthesize", "evaluate", "assess", "judge", "criticize",
    "jump", "leap", "bound", "spring", "hop", "skip", "bounce", "vault", "soar", "fly", "glide", "hover",
    "dive", "plunge", "sink", "swim", "float", "drift", "sail", "navigate", "steer", "pilot", "drive", "ride",
    "walk", "run", "jog", "sprint", "dash", "stroll", "saunter", "amble", "wander", "roam", "explore", "traverse",
    }

# SENTENCES
sentence_formats = {
    "{setting} {descriptor} {obj}{plural}", "{setting} {descriptor}, {descriptor} {obj}{plural}",
    "{setting} {descriptor} {obj}{plural} {verb}s {setting}{obj}{plural}", "{descriptor} {obj}s",
    "{descriptor}, {descriptor} {obj}s", "a {descriptor} {obj}", "a {descriptor}, {descriptor} {obj}",
    "{obj}s {verb}ing", "{obj} {verb} from {descriptor} {obj}", "{descriptor} {obj} {verb}ing {obj}s",
    "{setting} {descriptor} {obj}{plural} {verb}ing", "a {obj}", "{obj}s", "{obj} studies",
    "{descriptor} {obj}s {verb} a {obj}", "{obj} that look like {obj}s", "{obj} - {obj} hybrid",
    "2 {obj}, 1 {obj}" "Mr. {obj}", "a person with a {obj} for a head", "a person with a {obj} for a leg",
    "a person with a {obj} for an arm", "a person with a {obj} for a hand", "a person with a {obj} for a foot",
    "a person with a {obj} for a nose", "a person with a {obj} for an ear", "a person with a {obj} for an eye",
    "a wide variety of {obj}s", "the best {obj} ever", "the worst {obj} ever",
    "the most {descriptor} {obj} ever", "the least {descriptor} {obj} ever", "the most {descriptor} {obj}s",
    "a {obj} that {verb}s", "a {obj} that {verb}s {obj}s", "applies for a job as a {obj}", "is pretending to be a {obj}",
    "can transform into a {obj}", "is a {obj}", "is a fan of {obj}s", "is a collector of {obj}s", "is a master of {obj}s",
    "is an expert in {obj}s", "is a novice at {obj}", "is a beginner at {obj}", "is a pro at {obj}"
    "is a specialist in {obj}s", "is a connoisseur of {obj}s", "is a lover of {obj}s", "is a hater of {obj}s",
    "is a champion at {obj}", "is a master at {obj}", "is a wizard of {obj}", "is a sorcerer of {obj}", "is a {obj} magician",
    "is a thief who steals {obj}s",  

}